stages:
  - test
  - build
  
test:
  image: node:latest
  stage: test
   script:
    - echo "This job tests something"
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run start:ci "&"
    - npm run pretest 
    # run Cypress tests
    - npm run mtest