name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        with:
            node-version: 20
            cache: 'npm'
            cache-dependency-path: subdir/package-lock.json
  

      - name: Cypress run

        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: actions/github-action@v6

       
        
        with:
          install: true
          project: C:\Users\sonam\OneDrive\Desktop\ME\MOCHA_ACCOUNTS
          command: npm cypress run
          config-file: cypress.config.js
          wait-on-timeout: 900
          browser: chrome
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: abab6f85-2f5f-4795-8d0b-c6d6cfa95bc7
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}