name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: C:\Users\sonam\OneDrive\Desktop\ME\MOCHA_ACCOUNTS
          browser: chrome
          build: npm build
          start: npm start
          wait-on: "http://localhost:3000"