name: example-config
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  start:
    # example where we pass custom base URL
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/config
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3333'
          

  config-file:
    # example where we use a custom config-file
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: cypress/TestMochaAccounts
          build: npm run build
          start: npm start
          
          config-file: cypress.config-alternate.js
