name: example-custom-command
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  start:
    # example where instead of forming the default "cypress run ..."
    # the user can specify their own command
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Custom tests 🧪
        uses: ./
        with:
          command:
             npm run pretest
             npm run mtest
          working-directory: ./

      - name: Show saved file
        run: cat ./mochawesome-report/mochawesome.html